// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// floyd_warshall_cpp
arma::mat floyd_warshall_cpp(const arma::mat& adjacency, bool weighted);
RcppExport SEXP _PhysioExperiment_floyd_warshall_cpp(SEXP adjacencySEXP, SEXP weightedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    rcpp_result_gen = Rcpp::wrap(floyd_warshall_cpp(adjacency, weighted));
    return rcpp_result_gen;
END_RCPP
}
// clustering_coefficient_cpp
arma::vec clustering_coefficient_cpp(const arma::mat& adjacency, bool weighted, int n_cores);
RcppExport SEXP _PhysioExperiment_clustering_coefficient_cpp(SEXP adjacencySEXP, SEXP weightedSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(clustering_coefficient_cpp(adjacency, weighted, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// node_degree_cpp
arma::vec node_degree_cpp(const arma::mat& adjacency, bool weighted);
RcppExport SEXP _PhysioExperiment_node_degree_cpp(SEXP adjacencySEXP, SEXP weightedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    rcpp_result_gen = Rcpp::wrap(node_degree_cpp(adjacency, weighted));
    return rcpp_result_gen;
END_RCPP
}
// betweenness_centrality_cpp
arma::vec betweenness_centrality_cpp(const arma::mat& adjacency, bool normalized, int n_cores);
RcppExport SEXP _PhysioExperiment_betweenness_centrality_cpp(SEXP adjacencySEXP, SEXP normalizedSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(betweenness_centrality_cpp(adjacency, normalized, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// find_clusters_cpp
List find_clusters_cpp(const arma::mat& t_matrix, double threshold, int tail);
RcppExport SEXP _PhysioExperiment_find_clusters_cpp(SEXP t_matrixSEXP, SEXP thresholdSEXP, SEXP tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t_matrix(t_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type tail(tailSEXP);
    rcpp_result_gen = Rcpp::wrap(find_clusters_cpp(t_matrix, threshold, tail));
    return rcpp_result_gen;
END_RCPP
}
// eigenvector_centrality_cpp
arma::vec eigenvector_centrality_cpp(const arma::mat& adjacency, int max_iter, double tol);
RcppExport SEXP _PhysioExperiment_eigenvector_centrality_cpp(SEXP adjacencySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenvector_centrality_cpp(adjacency, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// global_efficiency_cpp
double global_efficiency_cpp(const arma::mat& adjacency, bool weighted);
RcppExport SEXP _PhysioExperiment_global_efficiency_cpp(SEXP adjacencySEXP, SEXP weightedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjacency(adjacencySEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    rcpp_result_gen = Rcpp::wrap(global_efficiency_cpp(adjacency, weighted));
    return rcpp_result_gen;
END_RCPP
}
// compute_t_matrix_one_sample_cpp
arma::mat compute_t_matrix_one_sample_cpp(const arma::cube& data, double mu, int n_cores);
RcppExport SEXP _PhysioExperiment_compute_t_matrix_one_sample_cpp(SEXP dataSEXP, SEXP muSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_t_matrix_one_sample_cpp(data, mu, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// compute_t_matrix_two_sample_cpp
arma::mat compute_t_matrix_two_sample_cpp(const arma::cube& data1, const arma::cube& data2, int n_cores);
RcppExport SEXP _PhysioExperiment_compute_t_matrix_two_sample_cpp(SEXP data1SEXP, SEXP data2SEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_t_matrix_two_sample_cpp(data1, data2, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// compute_pvalues_cpp
arma::mat compute_pvalues_cpp(const arma::mat& t_matrix, const arma::mat& df_matrix, const std::string& alternative);
RcppExport SEXP _PhysioExperiment_compute_pvalues_cpp(SEXP t_matrixSEXP, SEXP df_matrixSEXP, SEXP alternativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t_matrix(t_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type df_matrix(df_matrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type alternative(alternativeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pvalues_cpp(t_matrix, df_matrix, alternative));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhysioExperiment_floyd_warshall_cpp", (DL_FUNC) &_PhysioExperiment_floyd_warshall_cpp, 2},
    {"_PhysioExperiment_clustering_coefficient_cpp", (DL_FUNC) &_PhysioExperiment_clustering_coefficient_cpp, 3},
    {"_PhysioExperiment_node_degree_cpp", (DL_FUNC) &_PhysioExperiment_node_degree_cpp, 2},
    {"_PhysioExperiment_betweenness_centrality_cpp", (DL_FUNC) &_PhysioExperiment_betweenness_centrality_cpp, 3},
    {"_PhysioExperiment_find_clusters_cpp", (DL_FUNC) &_PhysioExperiment_find_clusters_cpp, 3},
    {"_PhysioExperiment_eigenvector_centrality_cpp", (DL_FUNC) &_PhysioExperiment_eigenvector_centrality_cpp, 3},
    {"_PhysioExperiment_global_efficiency_cpp", (DL_FUNC) &_PhysioExperiment_global_efficiency_cpp, 2},
    {"_PhysioExperiment_compute_t_matrix_one_sample_cpp", (DL_FUNC) &_PhysioExperiment_compute_t_matrix_one_sample_cpp, 3},
    {"_PhysioExperiment_compute_t_matrix_two_sample_cpp", (DL_FUNC) &_PhysioExperiment_compute_t_matrix_two_sample_cpp, 3},
    {"_PhysioExperiment_compute_pvalues_cpp", (DL_FUNC) &_PhysioExperiment_compute_pvalues_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhysioExperiment(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
