# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

floyd_warshall_cpp <- function(adjacency, weighted = FALSE) {
    .Call(`_PhysioExperiment_floyd_warshall_cpp`, adjacency, weighted)
}

clustering_coefficient_cpp <- function(adjacency, weighted = FALSE, n_cores = 1L) {
    .Call(`_PhysioExperiment_clustering_coefficient_cpp`, adjacency, weighted, n_cores)
}

node_degree_cpp <- function(adjacency, weighted = FALSE) {
    .Call(`_PhysioExperiment_node_degree_cpp`, adjacency, weighted)
}

betweenness_centrality_cpp <- function(adjacency, normalized = TRUE, n_cores = 1L) {
    .Call(`_PhysioExperiment_betweenness_centrality_cpp`, adjacency, normalized, n_cores)
}

find_clusters_cpp <- function(t_matrix, threshold, tail = 0L) {
    .Call(`_PhysioExperiment_find_clusters_cpp`, t_matrix, threshold, tail)
}

eigenvector_centrality_cpp <- function(adjacency, max_iter = 100L, tol = 1e-6) {
    .Call(`_PhysioExperiment_eigenvector_centrality_cpp`, adjacency, max_iter, tol)
}

global_efficiency_cpp <- function(adjacency, weighted = FALSE) {
    .Call(`_PhysioExperiment_global_efficiency_cpp`, adjacency, weighted)
}

compute_t_matrix_one_sample_cpp <- function(data, mu = 0.0, n_cores = 1L) {
    .Call(`_PhysioExperiment_compute_t_matrix_one_sample_cpp`, data, mu, n_cores)
}

compute_t_matrix_two_sample_cpp <- function(data1, data2, n_cores = 1L) {
    .Call(`_PhysioExperiment_compute_t_matrix_two_sample_cpp`, data1, data2, n_cores)
}

compute_pvalues_cpp <- function(t_matrix, df_matrix, alternative = "two.sided") {
    .Call(`_PhysioExperiment_compute_pvalues_cpp`, t_matrix, df_matrix, alternative)
}

